#!/usr/bin/python3
#
#

import math

values = [ ]
for i in range(200):
	x = i / 200 * math.pi / 2
	y = round(140 + 115 * math.sin(x))
	values.append(y)

print("static const uint8_t sine_table[] PROGMEM = {")
perline = 16
for i in range(0, len(values), perline):
	chunk = values[i : i + 16]
	print("	%s" % (" ".join("%3d," % (v) for v in chunk)))
print("};")

#	print("%.0f," % ()
